# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 621532c0780e291a90e2b2b1a47ce90477ba96689c249467b82df529913a8db36eed341cf159b8eeac797528b63b3e02dba2135c5cdbc12c54eae044b5e348a0

test:
  secret_key_base: f6db00d718e7ab76220393f9d96fb1f3764ae0b165fe26716f2ceb77a0b7bacb538599897e608d75070550d4ebe993bd4c176f42773582e6a66aa1c02b00c9fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
